// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import EnvironmentOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/EnvironmentOutlined';
import CrownOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import UserOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/UserOutlined';
import ShoppingOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/ShoppingOutlined';
import TagOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/TagOutlined';
import ProfileOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import BarChartOutlined from '/Users/chaisimin/项目/练习/shop-platform-demo/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
export default { SmileOutlined, EnvironmentOutlined, CrownOutlined, UserOutlined, ShoppingOutlined, TagOutlined, ProfileOutlined, BarChartOutlined };
